// <auto-generated />
using System;
using ApprovalSchemeProcess.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApprovalSchemeProcess.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApprovalSchemeProcessDbContext))]
    partial class ApprovalSchemeProcessDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.Appointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CitizenDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("citizen_display_name");

                    b.Property<string>("CitizenIdentifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("citizen_identifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<long>("OperationTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("operation_type_id");

                    b.Property<DateTime>("ScheduledEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_end_at");

                    b.Property<DateTime>("ScheduledStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_start_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("scheduled")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_appointments");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_appointments_created_by_user_id");

                    b.HasIndex("OperationTypeId")
                        .HasDatabaseName("idx_appointments_operation_type");

                    b.ToTable("appointments", null, t =>
                        {
                            t.HasCheckConstraint("ck_appointments_schedule", "scheduled_end_at >= scheduled_start_at");
                        });
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.AppointmentTarget", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AppointmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("appointment_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<string>("TargetIdentifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_identifier");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_appointment_targets");

                    b.HasIndex("AppointmentId")
                        .HasDatabaseName("idx_appointment_targets_appointment");

                    b.ToTable("appointment_targets", (string)null);
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.Approval", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApprovalRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("approval_request_id");

                    b.Property<long>("ApprovalSchemeStepId")
                        .HasColumnType("bigint")
                        .HasColumnName("approval_scheme_step_id");

                    b.Property<long>("ApproverUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("approver_user_id");

                    b.Property<DateTime>("DecidedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("decision");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_approvals");

                    b.HasIndex("ApprovalRequestId")
                        .HasDatabaseName("idx_approvals_request");

                    b.HasIndex("ApprovalSchemeStepId")
                        .HasDatabaseName("ix_approvals_approval_scheme_step_id");

                    b.HasIndex("ApproverUserId")
                        .HasDatabaseName("ix_approvals_approver_user_id");

                    b.HasIndex("ApprovalRequestId", "ApprovalSchemeStepId")
                        .IsUnique()
                        .HasDatabaseName("uq_approvals_unique_step");

                    b.ToTable("approvals", null, t =>
                        {
                            t.HasCheckConstraint("ck_approvals_decision", "decision IN ('approved', 'denied', 'expired')");
                        });
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.ApprovalRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApprovalSchemeId")
                        .HasColumnType("bigint")
                        .HasColumnName("approval_scheme_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<long>("QueryId")
                        .HasColumnType("bigint")
                        .HasColumnName("query_id");

                    b.Property<DateTime>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_approval_requests");

                    b.HasIndex("ApprovalSchemeId")
                        .HasDatabaseName("idx_approval_requests_scheme");

                    b.HasIndex("QueryId")
                        .IsUnique()
                        .HasDatabaseName("ix_approval_requests_query_id");

                    b.ToTable("approval_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_approval_requests_status", "status IN ('pending', 'approved', 'denied', 'expired')");
                        });
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.ApprovalScheme", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("OperationTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("operation_type_id");

                    b.Property<DateTime?>("RetiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at");

                    b.Property<int>("VersionNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version_no");

                    b.HasKey("Id")
                        .HasName("pk_approval_schemes");

                    b.HasIndex("OperationTypeId")
                        .HasDatabaseName("idx_approval_schemes_operation_type");

                    b.HasIndex("OperationTypeId", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("uq_approval_schemes_unique_version");

                    b.ToTable("approval_schemes", (string)null);
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.ApprovalSchemeStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApprovalSchemeId")
                        .HasColumnType("bigint")
                        .HasColumnName("approval_scheme_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsMandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_mandatory");

                    b.Property<string>("ReviewType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("approval")
                        .HasColumnName("review_type");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role_code");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer")
                        .HasColumnName("step_order");

                    b.Property<int?>("TimeoutMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_minutes");

                    b.HasKey("Id")
                        .HasName("pk_approval_scheme_steps");

                    b.HasIndex("ApprovalSchemeId")
                        .HasDatabaseName("idx_approval_scheme_steps_scheme");

                    b.HasIndex("ApprovalSchemeId", "StepOrder")
                        .IsUnique()
                        .HasDatabaseName("uq_approval_scheme_steps_order");

                    b.ToTable("approval_scheme_steps", null, t =>
                        {
                            t.HasCheckConstraint("ck_approval_scheme_steps_order", "step_order > 0");

                            t.HasCheckConstraint("ck_approval_scheme_steps_timeout", "timeout_minutes IS NULL OR timeout_minutes > 0");
                        });
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ActorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("DeviceIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("device_identifier");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_logs_actor_user_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("idx_audit_logs_occurred_at");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("idx_audit_logs_entity");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.OperationType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("SecurityLevelId")
                        .HasColumnType("bigint")
                        .HasColumnName("security_level_id");

                    b.HasKey("Id")
                        .HasName("pk_operation_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_operation_types_code");

                    b.HasIndex("SecurityLevelId")
                        .HasDatabaseName("idx_operation_types_security_level");

                    b.ToTable("operation_types", (string)null);
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.Query", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<bool>("IsEmergency")
                        .HasColumnType("boolean")
                        .HasColumnName("is_emergency");

                    b.Property<bool>("IsOverride")
                        .HasColumnType("boolean")
                        .HasColumnName("is_override");

                    b.Property<string>("Justification")
                        .HasColumnType("text")
                        .HasColumnName("justification");

                    b.Property<long>("OperationTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("operation_type_id");

                    b.Property<string>("RequestClassification")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("request_classification");

                    b.Property<DateTime>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("RequestedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("requested_by_user_id");

                    b.Property<long>("SecurityLevelId")
                        .HasColumnType("bigint")
                        .HasColumnName("security_level_id");

                    b.Property<long?>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("TargetIdentifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_identifier");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_queries");

                    b.HasIndex("OperationTypeId")
                        .HasDatabaseName("idx_queries_operation_type");

                    b.HasIndex("RequestedByUserId")
                        .HasDatabaseName("idx_queries_requested_by");

                    b.HasIndex("SecurityLevelId")
                        .HasDatabaseName("idx_queries_security_level");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("idx_queries_session");

                    b.ToTable("queries", null, t =>
                        {
                            t.HasCheckConstraint("ck_queries_classification", "request_classification IN ('in_context', 'out_of_context')");

                            t.HasCheckConstraint("ck_queries_status", "status IN ('pending', 'approved', 'denied', 'expired', 'executed')");
                        });
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_code");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.SecurityLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("LevelCode")
                        .HasColumnType("integer")
                        .HasColumnName("level_code");

                    b.Property<int>("MinApprovalSteps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("min_approval_steps");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresApproval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("requires_approval");

                    b.Property<bool>("RequiresComplianceReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("requires_compliance_review");

                    b.Property<bool>("RequiresSpecialAuthorization")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("requires_special_authorization");

                    b.HasKey("Id")
                        .HasName("pk_security_levels");

                    b.HasIndex("LevelCode")
                        .IsUnique()
                        .HasDatabaseName("ix_security_levels_level_code");

                    b.ToTable("security_levels", null, t =>
                        {
                            t.HasCheckConstraint("ck_security_levels_level_code", "level_code BETWEEN 0 AND 4");

                            t.HasCheckConstraint("ck_security_levels_min_steps", "min_approval_steps >= 0");
                        });
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ActivatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("AppointmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("appointment_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("CurrentAssignedUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("current_assigned_user_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("InvalidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invalidated_at");

                    b.Property<string>("InvalidationReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("invalidation_reason");

                    b.Property<DateTime>("LastActivityAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_sessions_appointment_id");

                    b.HasIndex("CurrentAssignedUserId")
                        .HasDatabaseName("idx_sessions_current_assigned_user");

                    b.ToTable("sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_sessions_close_time", "closed_at IS NULL OR closed_at >= activated_at");

                            t.HasCheckConstraint("ck_sessions_expiry_time", "expires_at IS NULL OR expires_at >= activated_at");

                            t.HasCheckConstraint("ck_sessions_invalidation_reason", "(invalidated_at IS NULL AND invalidation_reason IS NULL) OR (invalidated_at IS NOT NULL AND invalidation_reason IS NOT NULL)");

                            t.HasCheckConstraint("ck_sessions_invalidation_time", "invalidated_at IS NULL OR invalidated_at >= activated_at");

                            t.HasCheckConstraint("ck_sessions_last_activity", "last_activity_at >= activated_at");

                            t.HasCheckConstraint("ck_sessions_status", "status IN ('pending_activation', 'active', 'paused', 'closed', 'expired', 'invalidated')");
                        });
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.SessionAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("AssignedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<string>("AssignmentReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("assignment_reason");

                    b.Property<string>("AssignmentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("primary")
                        .HasColumnName("assignment_type");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_current");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_session_assignments");

                    b.HasIndex("AssignedByUserId")
                        .HasDatabaseName("ix_session_assignments_assigned_by_user_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("idx_session_assignments_session");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_session_assignments_user");

                    b.HasIndex("SessionId", "IsCurrent")
                        .HasDatabaseName("idx_session_assignments_current");

                    b.HasIndex("SessionId", "UserId", "AssignedAt")
                        .IsUnique()
                        .HasDatabaseName("uq_session_assignments_unique");

                    b.ToTable("session_assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_session_assignments_current", "(is_current = TRUE AND released_at IS NULL) OR (is_current = FALSE AND released_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_session_assignments_release_time", "released_at IS NULL OR released_at >= assigned_at");

                            t.HasCheckConstraint("ck_session_assignments_type", "assignment_type IN ('primary', 'delegate', 'temporary', 'reassigned')");
                        });
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("employee_number");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_users_employee_number");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("idx_user_roles_role");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_user_roles_user");

                    b.HasIndex("UserId", "RoleId", "ValidFrom")
                        .IsUnique()
                        .HasDatabaseName("uq_user_roles_unique");

                    b.ToTable("user_roles", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_roles_validity", "valid_to IS NULL OR valid_to >= valid_from");
                        });
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("ApprovalSchemeProcess.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedAppointments")
                        .HasForeignKey("CreatedByUserId")
                        .HasConstraintName("fk_appointments_users_created_by_user_id");

                    b.HasOne("ApprovalSchemeProcess.Domain.Entities.OperationType", "OperationType")
                        .WithMany("Appointments")
                        .HasForeignKey("OperationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_operation_types_operation_type_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("OperationType");
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.AppointmentTarget", b =>
                {
                    b.HasOne("ApprovalSchemeProcess.Domain.Entities.Appointment", "Appointment")
                        .WithMany("Targets")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointment_targets_appointments_appointment_id");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.Approval", b =>
                {
                    b.HasOne("ApprovalSchemeProcess.Domain.Entities.ApprovalRequest", "ApprovalRequest")
                        .WithMany("Approvals")
                        .HasForeignKey("ApprovalRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_approvals_approval_requests_approval_request_id");

                    b.HasOne("ApprovalSchemeProcess.Domain.Entities.ApprovalSchemeStep", "ApprovalSchemeStep")
                        .WithMany("Approvals")
                        .HasForeignKey("ApprovalSchemeStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_approvals_approval_scheme_steps_approval_scheme_step_id");

                    b.HasOne("ApprovalSchemeProcess.Domain.Entities.User", "ApproverUser")
                        .WithMany("Approvals")
                        .HasForeignKey("ApproverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_approvals_users_approver_user_id");

                    b.Navigation("ApprovalRequest");

                    b.Navigation("ApprovalSchemeStep");

                    b.Navigation("ApproverUser");
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.ApprovalRequest", b =>
                {
                    b.HasOne("ApprovalSchemeProcess.Domain.Entities.ApprovalScheme", "ApprovalScheme")
                        .WithMany("ApprovalRequests")
                        .HasForeignKey("ApprovalSchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_approval_requests_approval_schemes_approval_scheme_id");

                    b.HasOne("ApprovalSchemeProcess.Domain.Entities.Query", "Query")
                        .WithOne("ApprovalRequest")
                        .HasForeignKey("ApprovalSchemeProcess.Domain.Entities.ApprovalRequest", "QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_approval_requests_queries_query_id");

                    b.Navigation("ApprovalScheme");

                    b.Navigation("Query");
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.ApprovalScheme", b =>
                {
                    b.HasOne("ApprovalSchemeProcess.Domain.Entities.OperationType", "OperationType")
                        .WithMany("ApprovalSchemes")
                        .HasForeignKey("OperationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_approval_schemes_operation_types_operation_type_id");

                    b.Navigation("OperationType");
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.ApprovalSchemeStep", b =>
                {
                    b.HasOne("ApprovalSchemeProcess.Domain.Entities.ApprovalScheme", "ApprovalScheme")
                        .WithMany("Steps")
                        .HasForeignKey("ApprovalSchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_approval_scheme_steps_approval_schemes_approval_scheme_id");

                    b.Navigation("ApprovalScheme");
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("ApprovalSchemeProcess.Domain.Entities.User", "ActorUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_logs_users_actor_user_id");

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.OperationType", b =>
                {
                    b.HasOne("ApprovalSchemeProcess.Domain.Entities.SecurityLevel", "SecurityLevel")
                        .WithMany("OperationTypes")
                        .HasForeignKey("SecurityLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_operation_types_security_levels_security_level_id");

                    b.Navigation("SecurityLevel");
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.Query", b =>
                {
                    b.HasOne("ApprovalSchemeProcess.Domain.Entities.OperationType", "OperationType")
                        .WithMany("Queries")
                        .HasForeignKey("OperationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_queries_operation_types_operation_type_id");

                    b.HasOne("ApprovalSchemeProcess.Domain.Entities.User", "RequestedByUser")
                        .WithMany("RequestedQueries")
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_queries_users_requested_by_user_id");

                    b.HasOne("ApprovalSchemeProcess.Domain.Entities.SecurityLevel", "SecurityLevel")
                        .WithMany("Queries")
                        .HasForeignKey("SecurityLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_queries_security_levels_security_level_id");

                    b.HasOne("ApprovalSchemeProcess.Domain.Entities.Session", "Session")
                        .WithMany("Queries")
                        .HasForeignKey("SessionId")
                        .HasConstraintName("fk_queries_sessions_session_id");

                    b.Navigation("OperationType");

                    b.Navigation("RequestedByUser");

                    b.Navigation("SecurityLevel");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.Session", b =>
                {
                    b.HasOne("ApprovalSchemeProcess.Domain.Entities.Appointment", "Appointment")
                        .WithOne("Session")
                        .HasForeignKey("ApprovalSchemeProcess.Domain.Entities.Session", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_appointments_appointment_id");

                    b.HasOne("ApprovalSchemeProcess.Domain.Entities.User", "CurrentAssignedUser")
                        .WithMany("CurrentAssignedSessions")
                        .HasForeignKey("CurrentAssignedUserId")
                        .HasConstraintName("fk_sessions_users_current_assigned_user_id");

                    b.Navigation("Appointment");

                    b.Navigation("CurrentAssignedUser");
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.SessionAssignment", b =>
                {
                    b.HasOne("ApprovalSchemeProcess.Domain.Entities.User", "AssignedByUser")
                        .WithMany("AssignedSessionActions")
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_session_assignments_users_assigned_by_user_id");

                    b.HasOne("ApprovalSchemeProcess.Domain.Entities.Session", "Session")
                        .WithMany("Assignments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_assignments_sessions_session_id");

                    b.HasOne("ApprovalSchemeProcess.Domain.Entities.User", "User")
                        .WithMany("SessionAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_session_assignments_users_user_id");

                    b.Navigation("AssignedByUser");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("ApprovalSchemeProcess.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("ApprovalSchemeProcess.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("Session");

                    b.Navigation("Targets");
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.ApprovalRequest", b =>
                {
                    b.Navigation("Approvals");
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.ApprovalScheme", b =>
                {
                    b.Navigation("ApprovalRequests");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.ApprovalSchemeStep", b =>
                {
                    b.Navigation("Approvals");
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.OperationType", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ApprovalSchemes");

                    b.Navigation("Queries");
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.Query", b =>
                {
                    b.Navigation("ApprovalRequest");
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.SecurityLevel", b =>
                {
                    b.Navigation("OperationTypes");

                    b.Navigation("Queries");
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.Session", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Queries");
                });

            modelBuilder.Entity("ApprovalSchemeProcess.Domain.Entities.User", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("AssignedSessionActions");

                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedAppointments");

                    b.Navigation("CurrentAssignedSessions");

                    b.Navigation("RequestedQueries");

                    b.Navigation("SessionAssignments");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
